create table greeting
(
    id          bigint generated by default as identity,
    created     timestamp,
    updated     timestamp,
    version     bigint,
    greeting_id uuid         not null,
    name        varchar(255) not null unique,
    salutes     integer      not null,
    primary key (id)
);